export const COUNTRY_FLAGS: Record<string, string> = {
  Afghanistan: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/afghanistan.svg",
  Albania: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/albania.svg",
  Algeria: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/algeria.svg",
  Andorra: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/andorra.svg",
  Angola: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/angola.svg",
  AntiguaAndBarbuda: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/antigua-and-barbuda.svg",
  Argentina: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/argentina.svg",
  Armenia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/armenia.svg",
  Australia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/australia.svg",
  Austria: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/austria.svg",
  Azerbaijan: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/azerbaijan.svg",
  Bahamas: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/bahamas.svg",
  Bahrain: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/bahrain.svg",
  Bangladesh: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/bangladesh.svg",
  Barbados: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/barbados.svg",
  Belarus: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/belarus.svg",
  Belgium: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/belgium.svg",
  Belize: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/belize.svg",
  Benin: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/benin.svg",
  Bhutan: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/bhutan.svg",
  Bolivia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/bolivia.svg",
  BosniaAndHerzegovina: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/bosnia-and-herzegovina.svg",
  Botswana: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/botswana.svg",
  Brazil: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/brazil.svg",
  Brunei: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/brunei.svg",
  Bulgaria: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/bulgaria.svg",
  BurkinaFaso: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/burkina-faso.svg",
  Burundi: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/burundi.svg",
  CaboVerde: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/cabo-verde.svg",
  Cambodia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/cambodia.svg",
  Cameroon: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/cameroon.svg",
  Canada: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/canada.svg",
  CentralAfricanRepublic: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/central-african-republic.svg",
  Chad: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/chad.svg",
  Chile: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/chile.svg",
  China: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/china.svg",
  Colombia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/colombia.svg",
  Comoros: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/comoros.svg",
  Congo: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/congo.svg",
  CostaRica: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/costa-rica.svg",
  Croatia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/croatia.svg",
  Cuba: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/cuba.svg",
  Cyprus: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/cyprus.svg",
  CzechRepublic: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/czech-republic.svg",
  Denmark: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/denmark.svg",
  Djibouti: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/djibouti.svg",
  Dominica: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/dominica.svg",
  DominicanRepublic: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/dominican-republic.svg",
  Ecuador: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/ecuador.svg",
  Egypt: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/egypt.svg",
  ElSalvador: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/el-salvador.svg",
  EquatorialGuinea: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/equatorial-guinea.svg",
  Eritrea: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/eritrea.svg",
  Estonia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/estonia.svg",
  Eswatini: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/eswatini.svg",
  Ethiopia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/ethiopia.svg",
  Fiji: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/fiji.svg",
  Finland: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/finland.svg",
  France: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/france.svg",
  Gabon: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/gabon.svg",
  Gambia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/gambia.svg",
  Georgia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/georgia.svg",
  Germany: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/germany.svg",
  Ghana: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/ghana.svg",
  Greece: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/greece.svg",
  Grenada: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/grenada.svg",
  Guatemala: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/guatemala.svg",
  Guinea: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/guinea.svg",
  GuineaBissau: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/guinea-bissau.svg",
  Guyana: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/guyana.svg",
  Haiti: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/haiti.svg",
  Honduras: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/honduras.svg",
  Hungary: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/hungary.svg",
  Iceland: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/iceland.svg",
  India: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/india.svg",
  Indonesia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/indonesia.svg",
  Iran: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/iran.svg",
  Iraq: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/iraq.svg",
  Ireland: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/ireland.svg",
  Israel: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/israel.svg",
  Italy: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/italy.svg",
  Jamaica: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/jamaica.svg",
  Japan: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/japan.svg",
  Jordan: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/jordan.svg",
  Kazakhstan: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/kazakhstan.svg",
  Kenya: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/kenya.svg",
  Kiribati: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/kiribati.svg",
  Kuwait: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/kuwait.svg",
  Kyrgyzstan: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/kyrgyzstan.svg",
  Laos: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/laos.svg",
  Latvia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/latvia.svg",
  Lebanon: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/lebanon.svg",
  Lesotho: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/lesotho.svg",
  Liberia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/liberia.svg",
  Libya: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/libya.svg",
  Liechtenstein: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/liechtenstein.svg",
  Lithuania: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/lithuania.svg",
  Luxembourg: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/luxembourg.svg",
  Madagascar: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/madagascar.svg",
  Malawi: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/malawi.svg",
  Malaysia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/malaysia.svg",
  Maldives: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/maldives.svg",
  Mali: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/mali.svg",
  Malta: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/malta.svg",
  MarshallIslands: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/marshall-islands.svg",
  Mauritania: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/mauritania.svg",
  Mauritius: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/mauritius.svg",
  Mexico: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/mexico.svg",
  Micronesia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/micronesia.svg",
  Moldova: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/moldova.svg",
  Monaco: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/monaco.svg",
  Mongolia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/mongolia.svg",
  Montenegro: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/montenegro.svg",
  Morocco: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/morocco.svg",
  Mozambique: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/mozambique.svg",
  Myanmar: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/myanmar.svg",
  Namibia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/namibia.svg",
  Nauru: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/nauru.svg",
  Nepal: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/nepal.svg",
  Netherlands: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/netherlands.svg",
  NewZealand: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/new-zealand.svg",
  Nicaragua: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/nicaragua.svg",
  Niger: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/niger.svg",
  Nigeria: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/nigeria.svg",
  NorthKorea: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/north-korea.svg",
  NorthMacedonia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/north-macedonia.svg",
  Norway: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/norway.svg",
  Oman: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/oman.svg",
  Pakistan: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/pakistan.svg",
  Palau: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/palau.svg",
  Palestine: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/palestine.svg",
  Panama: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/panama.svg",
  PapuaNewGuinea: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/papua-new-guinea.svg",
  Paraguay: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/paraguay.svg",
  Peru: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/peru.svg",
  Philippines: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/philippines.svg",
  Poland: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/poland.svg",
  Portugal: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/portugal.svg",
  Qatar: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/qatar.svg",
  Romania: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/romania.svg",
  Russia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/russia.svg",
  Rwanda: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/rwanda.svg",
  SaintKittsAndNevis: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/saint-kitts-and-nevis.svg",
  SaintLucia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/saint-lucia.svg",
  SaintVincentAndTheGrenadines: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/saint-vincent-and-the-grenadines.svg",
  Samoa: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/samoa.svg",
  SanMarino: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/san-marino.svg",
  SaoTomeAndPrincipe: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/sao-tome-and-principe.svg",
  SaudiArabia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/saudi-arabia.svg",
  Senegal: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/senegal.svg",
  Serbia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/serbia.svg",
  Seychelles: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/seychelles.svg",
  SierraLeone: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/sierra-leone.svg",
  Singapore: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/singapore.svg",
  Slovakia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/slovakia.svg",
  Slovenia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/slovenia.svg",
  SolomonIslands: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/solomon-islands.svg",
  Somalia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/somalia.svg",
  SouthAfrica: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/south-africa.svg",
  SouthKorea: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/south-korea.svg",
  SouthSudan: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/south-sudan.svg",
  Spain: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/spain.svg",
  SriLanka: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/sri-lanka.svg",
  Sudan: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/sudan.svg",
  Suriname: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/suriname.svg",
  Sweden: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/sweden.svg",
  Switzerland: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/switzerland.svg",
  Syria: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/syria.svg",
  Taiwan: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/taiwan.svg",
  Tajikistan: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/tajikistan.svg",
  Tanzania: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/tanzania.svg",
  Thailand: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/thailand.svg",
  TimorLeste: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/timor-leste.svg",
  Togo: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/togo.svg",
  Tonga: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/tonga.svg",
  TrinidadAndTobago: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/trinidad-and-tobago.svg",
  Tunisia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/tunisia.svg",
  Turkey: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/turkey.svg",
  Turkmenistan: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/turkmenistan.svg",
  Tuvalu: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/tuvalu.svg",
  Uganda: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/uganda.svg",
  Ukraine: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/ukraine.svg",
  UnitedArabEmirates: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/uae.svg",
  UnitedKingdom: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/uk.svg",
  UnitedStates: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/usa.svg",
  Uruguay: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/uruguay.svg",
  Uzbekistan: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/uzbekistan.svg",
  Vanuatu: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/vanuatu.svg",
  VaticanCity: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/vatican-city.svg",
  Venezuela: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/venezuela.svg",
  Vietnam: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/vietnam.svg",
  Yemen: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/yemen.svg",
  Zambia: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/zambia.svg",
  Zimbabwe: "https://static-assets-prod.fnp.com/assets/images/custom/country-flags/zimbabwe.svg",
};

export type Language = {
  code: string;
  name: string;
  countryName: string;
  countryCode: string;
};

export const languages: Language[] = [
  { code: "AF", name: "Pashto", countryName: "Afghanistan", countryCode: "AF" },
  { code: "AL", name: "Albanian", countryName: "Albania", countryCode: "AL" },
  { code: "DZ", name: "Arabic", countryName: "Algeria", countryCode: "DZ" },
  { code: "AD", name: "Catalan", countryName: "Andorra", countryCode: "AD" },
  { code: "AO", name: "Portuguese", countryName: "Angola", countryCode: "AO" },
  { code: "AR", name: "Spanish", countryName: "Argentina", countryCode: "AR" },
  { code: "AM", name: "Armenian", countryName: "Armenia", countryCode: "AM" },
  { code: "AU", name: "English", countryName: "Australia", countryCode: "AU" },
  { code: "AT", name: "German", countryName: "Austria", countryCode: "AT" },
  { code: "AZ", name: "Azerbaijani", countryName: "Azerbaijan", countryCode: "AZ" },
  { code: "BS", name: "English", countryName: "Bahamas", countryCode: "BS" },
  { code: "BH", name: "Arabic", countryName: "Bahrain", countryCode: "BH" },
  { code: "BD", name: "Bengali", countryName: "Bangladesh", countryCode: "BD" },
  { code: "BB", name: "English", countryName: "Barbados", countryCode: "BB" },
  { code: "BY", name: "Belarusian", countryName: "Belarus", countryCode: "BY" },
  { code: "BE", name: "Dutch", countryName: "Belgium", countryCode: "BE" },
  { code: "BZ", name: "English", countryName: "Belize", countryCode: "BZ" },
  { code: "BJ", name: "French", countryName: "Benin", countryCode: "BJ" },
  { code: "BT", name: "Dzongkha", countryName: "Bhutan", countryCode: "BT" },
  { code: "BO", name: "Spanish", countryName: "Bolivia", countryCode: "BO" },
  { code: "BA", name: "Bosnian", countryName: "Bosnia and Herzegovina", countryCode: "BA" },
  { code: "BW", name: "English", countryName: "Botswana", countryCode: "BW" },
  { code: "BR", name: "Portuguese", countryName: "Brazil", countryCode: "BR" },
  { code: "BN", name: "Malay", countryName: "Brunei", countryCode: "BN" },
  { code: "BG", name: "Bulgarian", countryName: "Bulgaria", countryCode: "BG" },
  { code: "BF", name: "French", countryName: "Burkina Faso", countryCode: "BF" },
  { code: "BI", name: "French", countryName: "Burundi", countryCode: "BI" },
  { code: "KH", name: "Khmer", countryName: "Cambodia", countryCode: "KH" },
  { code: "CM", name: "French", countryName: "Cameroon", countryCode: "CM" },
  { code: "CA", name: "English", countryName: "Canada", countryCode: "CA" },
  { code: "TD", name: "French", countryName: "Chad", countryCode: "TD" },
  { code: "CL", name: "Spanish", countryName: "Chile", countryCode: "CL" },
  { code: "CN", name: "Chinese", countryName: "China", countryCode: "CN" },
  { code: "CO", name: "Spanish", countryName: "Colombia", countryCode: "CO" },
  { code: "CR", name: "Spanish", countryName: "Costa Rica", countryCode: "CR" },
  { code: "HR", name: "Croatian", countryName: "Croatia", countryCode: "HR" },
  { code: "CY", name: "Greek", countryName: "Cyprus", countryCode: "CY" },
  { code: "CZ", name: "Czech", countryName: "Czech Republic", countryCode: "CZ" },
  { code: "DK", name: "Danish", countryName: "Denmark", countryCode: "DK" },
  { code: "DO", name: "Spanish", countryName: "Dominican Republic", countryCode: "DO" },
  { code: "EC", name: "Spanish", countryName: "Ecuador", countryCode: "EC" },
  { code: "EG", name: "Arabic", countryName: "Egypt", countryCode: "EG" },
  { code: "SV", name: "Spanish", countryName: "El Salvador", countryCode: "SV" },
  { code: "EE", name: "Estonian", countryName: "Estonia", countryCode: "EE" },
  { code: "ET", name: "Amharic", countryName: "Ethiopia", countryCode: "ET" },
  { code: "FJ", name: "English", countryName: "Fiji", countryCode: "FJ" },
  { code: "FI", name: "Finnish", countryName: "Finland", countryCode: "FI" },
  { code: "FR", name: "French", countryName: "France", countryCode: "FR" },
  { code: "GE", name: "Georgian", countryName: "Georgia", countryCode: "GE" },
  { code: "DE", name: "German", countryName: "Germany", countryCode: "DE" },
  { code: "GH", name: "English", countryName: "Ghana", countryCode: "GH" },
  { code: "GR", name: "Greek", countryName: "Greece", countryCode: "GR" },
  { code: "GT", name: "Spanish", countryName: "Guatemala", countryCode: "GT" },
  { code: "HT", name: "French", countryName: "Haiti", countryCode: "HT" },
  { code: "HN", name: "Spanish", countryName: "Honduras", countryCode: "HN" },
  { code: "HU", name: "Hungarian", countryName: "Hungary", countryCode: "HU" },
  { code: "IS", name: "Icelandic", countryName: "Iceland", countryCode: "IS" },
  { code: "IN", name: "English", countryName: "India", countryCode: "IN" },
  { code: "ID", name: "Indonesian", countryName: "Indonesia", countryCode: "ID" },
  { code: "IR", name: "Persian", countryName: "Iran", countryCode: "IR" },
  { code: "IQ", name: "Arabic", countryName: "Iraq", countryCode: "IQ" },
  { code: "IE", name: "English", countryName: "Ireland", countryCode: "IE" },
  { code: "IL", name: "Hebrew", countryName: "Israel", countryCode: "IL" },
  { code: "IT", name: "Italian", countryName: "Italy", countryCode: "IT" },
  { code: "JM", name: "English", countryName: "Jamaica", countryCode: "JM" },
  { code: "JP", name: "Japanese", countryName: "Japan", countryCode: "JP" },
  { code: "JO", name: "Arabic", countryName: "Jordan", countryCode: "JO" },
  { code: "KZ", name: "Kazakh", countryName: "Kazakhstan", countryCode: "KZ" },
  { code: "KE", name: "English", countryName: "Kenya", countryCode: "KE" },
  { code: "KW", name: "Arabic", countryName: "Kuwait", countryCode: "KW" },
  { code: "KG", name: "Kyrgyz", countryName: "Kyrgyzstan", countryCode: "KG" },
  { code: "LA", name: "Lao", countryName: "Laos", countryCode: "LA" },
  { code: "LV", name: "Latvian", countryName: "Latvia", countryCode: "LV" },
  { code: "LB", name: "Arabic", countryName: "Lebanon", countryCode: "LB" },
  { code: "LI", name: "German", countryName: "Liechtenstein", countryCode: "LI" },
  { code: "LT", name: "Lithuanian", countryName: "Lithuania", countryCode: "LT" },
  { code: "LU", name: "Luxembourgish", countryName: "Luxembourg", countryCode: "LU" },
  { code: "MG", name: "Malagasy", countryName: "Madagascar", countryCode: "MG" },
  { code: "MW", name: "English", countryName: "Malawi", countryCode: "MW" },
  { code: "MY", name: "Malay", countryName: "Malaysia", countryCode: "MY" },
  { code: "MV", name: "Dhivehi", countryName: "Maldives", countryCode: "MV" },
  { code: "MT", name: "Maltese", countryName: "Malta", countryCode: "MT" },
  { code: "MU", name: "English", countryName: "Mauritius", countryCode: "MU" },
  { code: "MX", name: "Spanish", countryName: "Mexico", countryCode: "MX" },
  { code: "MD", name: "Romanian", countryName: "Moldova", countryCode: "MD" },
  { code: "MC", name: "French", countryName: "Monaco", countryCode: "MC" },
  { code: "MN", name: "Mongolian", countryName: "Mongolia", countryCode: "MN" },
  { code: "ME", name: "Montenegrin", countryName: "Montenegro", countryCode: "ME" },
  { code: "MA", name: "Arabic", countryName: "Morocco", countryCode: "MA" },
  { code: "MZ", name: "Portuguese", countryName: "Mozambique", countryCode: "MZ" },
  { code: "MM", name: "Burmese", countryName: "Myanmar", countryCode: "MM" },
  { code: "NA", name: "English", countryName: "Namibia", countryCode: "NA" },
  { code: "NP", name: "Nepali", countryName: "Nepal", countryCode: "NP" },
  { code: "NL", name: "Dutch", countryName: "Netherlands", countryCode: "NL" },
  { code: "NZ", name: "English", countryName: "New Zealand", countryCode: "NZ" },
  { code: "NI", name: "Spanish", countryName: "Nicaragua", countryCode: "NI" },
  { code: "NE", name: "French", countryName: "Niger", countryCode: "NE" },
  { code: "NG", name: "English", countryName: "Nigeria", countryCode: "NG" },
  { code: "MK", name: "Macedonian", countryName: "North Macedonia", countryCode: "MK" },
  { code: "NO", name: "Norwegian", countryName: "Norway", countryCode: "NO" },
  { code: "OM", name: "Arabic", countryName: "Oman", countryCode: "OM" },
  { code: "PK", name: "Urdu", countryName: "Pakistan", countryCode: "PK" },
  { code: "PA", name: "Spanish", countryName: "Panama", countryCode: "PA" },
  { code: "PG", name: "English", countryName: "Papua New Guinea", countryCode: "PG" },
  { code: "PY", name: "Spanish", countryName: "Paraguay", countryCode: "PY" },
  { code: "PE", name: "Spanish", countryName: "Peru", countryCode: "PE" },
  { code: "PH", name: "English", countryName: "Philippines", countryCode: "PH" },
  { code: "PL", name: "Polish", countryName: "Poland", countryCode: "PL" },
  { code: "PT", name: "Portuguese", countryName: "Portugal", countryCode: "PT" },
  { code: "QA", name: "Arabic", countryName: "Qatar", countryCode: "QA" },
  { code: "RO", name: "Romanian", countryName: "Romania", countryCode: "RO" },
  { code: "RU", name: "Russian", countryName: "Russia", countryCode: "RU" },
  { code: "RW", name: "Kinyarwanda", countryName: "Rwanda", countryCode: "RW" },
  { code: "SA", name: "Arabic", countryName: "Saudi Arabia", countryCode: "SA" },
  { code: "SN", name: "French", countryName: "Senegal", countryCode: "SN" },
  { code: "RS", name: "Serbian", countryName: "Serbia", countryCode: "RS" },
  { code: "SG", name: "English", countryName: "Singapore", countryCode: "SG" },
  { code: "SK", name: "Slovak", countryName: "Slovakia", countryCode: "SK" },
  { code: "SI", name: "Slovenian", countryName: "Slovenia", countryCode: "SI" },
  { code: "SO", name: "Somali", countryName: "Somalia", countryCode: "SO" },
  { code: "ZA", name: "English", countryName: "South Africa", countryCode: "ZA" },
  { code: "KR", name: "Korean", countryName: "South Korea", countryCode: "KR" },
  { code: "SS", name: "English", countryName: "South Sudan", countryCode: "SS" },
  { code: "ES", name: "Spanish", countryName: "Spain", countryCode: "ES" },
  { code: "LK", name: "Sinhala", countryName: "Sri Lanka", countryCode: "LK" },
  { code: "SD", name: "Arabic", countryName: "Sudan", countryCode: "SD" },
  { code: "SR", name: "Dutch", countryName: "Suriname", countryCode: "SR" },
  { code: "SE", name: "Swedish", countryName: "Sweden", countryCode: "SE" },
  { code: "CH", name: "German", countryName: "Switzerland", countryCode: "CH" },
  { code: "SY", name: "Arabic", countryName: "Syria", countryCode: "SY" },
  { code: "TW", name: "Chinese", countryName: "Taiwan", countryCode: "TW" },
  { code: "TJ", name: "Tajik", countryName: "Tajikistan", countryCode: "TJ" },
  { code: "TZ", name: "Swahili", countryName: "Tanzania", countryCode: "TZ" },
  { code: "TH", name: "Thai", countryName: "Thailand", countryCode: "TH" },
  { code: "TL", name: "Portuguese", countryName: "Timor-Leste", countryCode: "TL" },
  { code: "TG", name: "French", countryName: "Togo", countryCode: "TG" },
  { code: "TO", name: "Tongan", countryName: "Tonga", countryCode: "TO" },
  { code: "TT", name: "English", countryName: "Trinidad and Tobago", countryCode: "TT" },
  { code: "TN", name: "Arabic", countryName: "Tunisia", countryCode: "TN" },
  { code: "TR", name: "Turkish", countryName: "Turkey", countryCode: "TR" },
  { code: "TM", name: "Turkmen", countryName: "Turkmenistan", countryCode: "TM" },
  { code: "UG", name: "English", countryName: "Uganda", countryCode: "UG" },
  { code: "UA", name: "Ukrainian", countryName: "Ukraine", countryCode: "UA" },
  { code: "AE", name: "Arabic", countryName: "United Arab Emirates", countryCode: "AE" },
  { code: "GB", name: "English", countryName: "United Kingdom", countryCode: "GB" },
  { code: "US", name: "English", countryName: "United States", countryCode: "US" },
  { code: "UY", name: "Spanish", countryName: "Uruguay", countryCode: "UY" },
  { code: "UZ", name: "Uzbek", countryName: "Uzbekistan", countryCode: "UZ" },
  { code: "VU", name: "Bislama", countryName: "Vanuatu", countryCode: "VU" },
  { code: "VA", name: "Italian", countryName: "Vatican City", countryCode: "VA" },
  { code: "VE", name: "Spanish", countryName: "Venezuela", countryCode: "VE" },
  { code: "VN", name: "Vietnamese", countryName: "Vietnam", countryCode: "VN" },
  { code: "YE", name: "Arabic", countryName: "Yemen", countryCode: "YE" },
  { code: "ZM", name: "English", countryName: "Zambia", countryCode: "ZM" },
  { code: "ZW", name: "English", countryName: "Zimbabwe", countryCode: "ZW" },
];